--------------------------------------------------------
--  File created - dinsdag-april-23-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADRESSEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."ADRESSEN" 
   (	"POSTCODE" VARCHAR2(6 BYTE), 
	"HUISNUMMER" VARCHAR2(6 BYTE), 
	"INGANGSDATUM" DATE, 
	"EINDDATUM" DATE, 
	"TELEFOON" NUMBER(10,0), 
	"MED_MNR" NUMBER(4,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AFDELINGEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."AFDELINGEN" 
   (	"ANR" NUMBER(3,0), 
	"NAAM" VARCHAR2(20 BYTE), 
	"LOCATIE" VARCHAR2(20 BYTE), 
	"HOOFD" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURSUSSEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."CURSUSSEN" 
   (	"CODE" VARCHAR2(4 BYTE), 
	"OMSCHRIJVING" VARCHAR2(50 BYTE), 
	"TYPE" CHAR(3 BYTE), 
	"LENGTE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIE
--------------------------------------------------------

  CREATE TABLE "FAISAL"."HISTORIE" 
   (	"MNR" NUMBER(4,0), 
	"BEGINJAAR" NUMBER(4,0), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE, 
	"AFD" NUMBER(2,0), 
	"MAANDSAL" NUMBER(6,2), 
	"OPMERKINGEN" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSCHRIJVINGEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."INSCHRIJVINGEN" 
   (	"CURSIST" NUMBER(4,0), 
	"CURSUS" VARCHAR2(4 BYTE), 
	"BEGINDATUM" DATE, 
	"EVALUATIE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDEWERKERS
--------------------------------------------------------

  CREATE TABLE "FAISAL"."MEDEWERKERS" 
   (	"MNR" NUMBER(4,0), 
	"NAAM" VARCHAR2(12 BYTE), 
	"VOORL" VARCHAR2(5 BYTE), 
	"FUNCTIE" VARCHAR2(10 BYTE), 
	"CHEF" NUMBER(4,0), 
	"GBDATUM" DATE, 
	"MAANDSAL" NUMBER(6,2), 
	"COMM" NUMBER(6,2), 
	"AFD" NUMBER(2,0) DEFAULT 10
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDEWERKERS2
--------------------------------------------------------

  CREATE TABLE "FAISAL"."MEDEWERKERS2" 
   (	"MNR" NUMBER(4,0), 
	"NAAM" VARCHAR2(12 BYTE), 
	"VOORL" VARCHAR2(5 BYTE), 
	"FUNCTIE" VARCHAR2(10 BYTE), 
	"CHEF" NUMBER(4,0), 
	"GBDATUM" DATE, 
	"MAANDSAL" NUMBER(6,2), 
	"COMM" NUMBER(6,2), 
	"AFD" NUMBER(2,0), 
	"GESLACHT" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDEWERKERSKOPPIE
--------------------------------------------------------

  CREATE TABLE "FAISAL"."MEDEWERKERSKOPPIE" 
   (	"MNR" NUMBER(4,0), 
	"NAAM" VARCHAR2(12 BYTE), 
	"VOORL" VARCHAR2(5 BYTE), 
	"FUNCTIE" VARCHAR2(10 BYTE), 
	"CHEF" NUMBER(4,0), 
	"GBDATUM" DATE, 
	"MAANDSAL" NUMBER(6,2), 
	"COMM" NUMBER(6,2), 
	"AFD" NUMBER(2,0) DEFAULT 10, 
	"MEDEWERKERGESLACHT" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCHALEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."SCHALEN" 
   (	"SNR" NUMBER(2,0), 
	"ONDERGRENS" NUMBER(6,2), 
	"BOVENGRENS" NUMBER(6,2), 
	"TOELAGE" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UITVOERINGEN
--------------------------------------------------------

  CREATE TABLE "FAISAL"."UITVOERINGEN" 
   (	"CURSUS" VARCHAR2(4 BYTE), 
	"BEGINDATUM" DATE, 
	"DOCENT" NUMBER(4,0), 
	"LOCATIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index A_PRIMARYKEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."A_PRIMARYKEY" ON "FAISAL"."ADRESSEN" ("POSTCODE", "HUISNUMMER", "INGANGSDATUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007502
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."SYS_C007502" ON "FAISAL"."ADRESSEN" ("TELEFOON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index A_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."A_PK" ON "FAISAL"."AFDELINGEN" ("ANR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index A_NAAM_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."A_NAAM_UN" ON "FAISAL"."AFDELINGEN" ("NAAM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index C_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."C_PK" ON "FAISAL"."CURSUSSEN" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index H_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."H_PK" ON "FAISAL"."HISTORIE" ("MNR", "BEGINDATUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index I_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."I_PK" ON "FAISAL"."INSCHRIJVINGEN" ("CURSIST", "CURSUS", "BEGINDATUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."M_PK" ON "FAISAL"."MEDEWERKERS" ("MNR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index S_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."S_PK" ON "FAISAL"."SCHALEN" ("SNR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index U_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAISAL"."U_PK" ON "FAISAL"."UITVOERINGEN" ("CURSUS", "BEGINDATUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADRESSEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("POSTCODE" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("HUISNUMMER" CONSTRAINT "HUISNUM_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("INGANGSDATUM" CONSTRAINT "INGDAT_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("EINDDATUM" CONSTRAINT "EINDDAT_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("TELEFOON" CONSTRAINT "TELEN_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" MODIFY ("MED_MNR" CONSTRAINT "MED_MNR_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."ADRESSEN" ADD CONSTRAINT "POSTCODE_NN" CHECK (
    Substr (postcode,1,4) BETWEEN '1000' and '9999' AND 
    Substr (postcode,5,2) BETWEEN 'AA' and 'ZZ'
    ) ENABLE;
  ALTER TABLE "FAISAL"."ADRESSEN" ADD CONSTRAINT "A_BD_ED" CHECK (ingangsdatum < einddatum) ENABLE;
  ALTER TABLE "FAISAL"."ADRESSEN" ADD CONSTRAINT "A_PRIMARYKEY" PRIMARY KEY ("POSTCODE", "HUISNUMMER", "INGANGSDATUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FAISAL"."ADRESSEN" ADD UNIQUE ("TELEFOON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AFDELINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."AFDELINGEN" MODIFY ("NAAM" CONSTRAINT "A_NAAM_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."AFDELINGEN" MODIFY ("LOCATIE" CONSTRAINT "A_LOC_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_ANR_CHK" CHECK (mod(anr,10) = 0) ENABLE;
  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_NAAM_CHK" CHECK (naam = upper(naam)) ENABLE;
  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_LOC_CHK" CHECK (locatie = upper(locatie)) ENABLE;
  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_PK" PRIMARY KEY ("ANR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_NAAM_UN" UNIQUE ("NAAM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURSUSSEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."CURSUSSEN" MODIFY ("OMSCHRIJVING" CONSTRAINT "C_OMSCHR_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."CURSUSSEN" MODIFY ("TYPE" CONSTRAINT "C_TYPE_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."CURSUSSEN" MODIFY ("LENGTE" CONSTRAINT "C_LENGTE_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."CURSUSSEN" ADD CONSTRAINT "C_CODE_CHK" CHECK (code = upper(code)) ENABLE;
  ALTER TABLE "FAISAL"."CURSUSSEN" ADD CONSTRAINT "C_TYPE_CHK" CHECK (type in ('ALG','BLD','DSG')) ENABLE;
  ALTER TABLE "FAISAL"."CURSUSSEN" ADD CONSTRAINT "C_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIE
--------------------------------------------------------

  ALTER TABLE "FAISAL"."HISTORIE" MODIFY ("MNR" CONSTRAINT "H_MNR_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."HISTORIE" MODIFY ("BEGINJAAR" CONSTRAINT "H_BJAAR_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."HISTORIE" MODIFY ("BEGINDATUM" CONSTRAINT "H_BEGIN_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."HISTORIE" MODIFY ("AFD" CONSTRAINT "H_AFD_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."HISTORIE" MODIFY ("MAANDSAL" CONSTRAINT "H_SAL_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."HISTORIE" ADD CONSTRAINT "H_BEG_EIND" CHECK (begindatum < einddatum) ENABLE;
  ALTER TABLE "FAISAL"."HISTORIE" ADD CONSTRAINT "H_PK" PRIMARY KEY ("MNR", "BEGINDATUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSCHRIJVINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" MODIFY ("CURSIST" CONSTRAINT "I_CURSIST_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" MODIFY ("CURSUS" CONSTRAINT "I_CURSUS_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" MODIFY ("BEGINDATUM" CONSTRAINT "I_BEGIN_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" ADD CONSTRAINT "I_EVAL_CHK" CHECK (evaluatie in (1,2,3,4,5)) ENABLE;
  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" ADD CONSTRAINT "I_PK" PRIMARY KEY ("CURSIST", "CURSUS", "BEGINDATUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDEWERKERS
--------------------------------------------------------

  ALTER TABLE "FAISAL"."MEDEWERKERS" MODIFY ("NAAM" CONSTRAINT "M_NAAM_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS" MODIFY ("VOORL" CONSTRAINT "M_VOORL_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS" MODIFY ("GBDATUM" CONSTRAINT "M_GEBDAT_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS" MODIFY ("MAANDSAL" CONSTRAINT "M_MNDSAL_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS" ADD CONSTRAINT "M_MNR_CHK" CHECK (mnr > 7000) ENABLE;
  ALTER TABLE "FAISAL"."MEDEWERKERS" ADD CONSTRAINT "M_VERK_CHK" CHECK (LNNVL(functie = 'VERKOPER')=LNNVL(comm IS NOT NULL)) ENABLE;
  ALTER TABLE "FAISAL"."MEDEWERKERS" ADD CONSTRAINT "M_PK" PRIMARY KEY ("MNR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDEWERKERS2
--------------------------------------------------------

  ALTER TABLE "FAISAL"."MEDEWERKERS2" MODIFY ("NAAM" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS2" MODIFY ("VOORL" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS2" MODIFY ("GBDATUM" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS2" MODIFY ("MAANDSAL" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERS2" ADD CONSTRAINT "CK_GENDER" CHECK (geslacht in ('M', 'V')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDEWERKERSKOPPIE
--------------------------------------------------------

  ALTER TABLE "FAISAL"."MEDEWERKERSKOPPIE" MODIFY ("NAAM" CONSTRAINT "M_NAAM_NN2" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERSKOPPIE" MODIFY ("VOORL" CONSTRAINT "M_VOORL_NN2" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERSKOPPIE" MODIFY ("GBDATUM" CONSTRAINT "M_GEBDAT_NN2" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERSKOPPIE" MODIFY ("MAANDSAL" CONSTRAINT "M_MNDSAL_NN2" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."MEDEWERKERSKOPPIE" ADD CONSTRAINT "GESLACHT_CHECK" CHECK (MEDEWERKERGESLACHT in ('M','V')) ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHALEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."SCHALEN" MODIFY ("ONDERGRENS" CONSTRAINT "S_ONDER_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."SCHALEN" MODIFY ("BOVENGRENS" CONSTRAINT "S_BOVEN_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."SCHALEN" MODIFY ("TOELAGE" CONSTRAINT "S_TOELG_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."SCHALEN" ADD CONSTRAINT "S_ONDER_CHK" CHECK (ondergrens >= 0) ENABLE;
  ALTER TABLE "FAISAL"."SCHALEN" ADD CONSTRAINT "S_OND_BOV" CHECK (ondergrens <= bovengrens) ENABLE;
  ALTER TABLE "FAISAL"."SCHALEN" ADD CONSTRAINT "S_PK" PRIMARY KEY ("SNR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UITVOERINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."UITVOERINGEN" MODIFY ("CURSUS" CONSTRAINT "U_CURSUS_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."UITVOERINGEN" MODIFY ("BEGINDATUM" CONSTRAINT "U_BEGIN_NN" NOT NULL ENABLE);
  ALTER TABLE "FAISAL"."UITVOERINGEN" ADD CONSTRAINT "U_PK" PRIMARY KEY ("CURSUS", "BEGINDATUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADRESSEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."ADRESSEN" ADD CONSTRAINT "A_MED_FK" FOREIGN KEY ("MED_MNR")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFDELINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."AFDELINGEN" ADD CONSTRAINT "A_HOOFD_FK" FOREIGN KEY ("HOOFD")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIE
--------------------------------------------------------

  ALTER TABLE "FAISAL"."HISTORIE" ADD CONSTRAINT "H_MNR_FK" FOREIGN KEY ("MNR")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FAISAL"."HISTORIE" ADD CONSTRAINT "H_AFD_FK" FOREIGN KEY ("AFD")
	  REFERENCES "FAISAL"."AFDELINGEN" ("ANR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSCHRIJVINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" ADD CONSTRAINT "I_CURSIST_FK" FOREIGN KEY ("CURSIST")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ENABLE;
  ALTER TABLE "FAISAL"."INSCHRIJVINGEN" ADD CONSTRAINT "I_UITV_FK" FOREIGN KEY ("CURSUS", "BEGINDATUM")
	  REFERENCES "FAISAL"."UITVOERINGEN" ("CURSUS", "BEGINDATUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDEWERKERS
--------------------------------------------------------

  ALTER TABLE "FAISAL"."MEDEWERKERS" ADD CONSTRAINT "M_CHEF_FK" FOREIGN KEY ("CHEF")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ENABLE;
  ALTER TABLE "FAISAL"."MEDEWERKERS" ADD CONSTRAINT "M_AFD_FK" FOREIGN KEY ("AFD")
	  REFERENCES "FAISAL"."AFDELINGEN" ("ANR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UITVOERINGEN
--------------------------------------------------------

  ALTER TABLE "FAISAL"."UITVOERINGEN" ADD CONSTRAINT "U_CURSUS_FK" FOREIGN KEY ("CURSUS")
	  REFERENCES "FAISAL"."CURSUSSEN" ("CODE") ENABLE;
  ALTER TABLE "FAISAL"."UITVOERINGEN" ADD CONSTRAINT "U_DOCENT_FK" FOREIGN KEY ("DOCENT")
	  REFERENCES "FAISAL"."MEDEWERKERS" ("MNR") ENABLE;
